spring:
  # 접속 DB 설정
  datasource:
    url: "jdbc:mariadb://127.0.0.1:44327/USERINFO"
    username: "kaby1217"
    password: "Cubie159!@"
    driver-class-name: "org.mariadb.jdbc.Driver"

# Hibernate 설정
hibernate:
  ddl-auto: update
  dialect: org.hibernate.dialect.MySQL5Dialect
  show-sql: true

# JPA 설정
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  generate-ddl: true