# 포트 번호 설정
server:
  port: 8082
  servlet:
    context-path: /study
# 로그 설정
logging.level:
  org.springframework: INFO

spring:
  # 접속 DB 설정
  datasource:
    url: "jdbc:mariadb://localhost:44327/USERINFO?passwordCharacterEncoding=UTF-8"
    username: "kaby1217"
    password: "Cubie159!@"
    driver-class-name: "org.mariadb.jdbc.Driver"
#  hibernate: # Hibernate 설정
#    ddl-auto: create
#    dialect: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
#
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true

  # 스프링 시큐리티
  security:
    user:
      name: kaby1217
      password: 1217159
      roles: USER,ADMIN

  #JWT설정
  jwt:
    secret: dlrjgozldgoqhffurh?zz #비밀의 키
    expiration: 8640000 #만료시간
    # application.yml



