# 포트 번호 설정
server:
  port: 8082
  servlet:
    context-path: /study

#로그 레벨
logging:
  level:
    org.springframework: INFO

#스프링 설정
spring:
  thymeleat:
    check-template-location: true

  # 접속 DB 설정
  datasource:
    url: "jdbc:mariadb://127.0.0.1:44327/USERINFO"
    username: "kaby1217"
    password: "Cubie159!@"
    driver-class-name: "org.mariadb.jdbc.Driver"

  # Hibernate 설정
  hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

# JPA 설정
  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: false

  # 스프링 시큐리티
  security:
    user:
      name : kaby1217
      password : 1217159
      roles : USER,ADMIN


  #JWT설정
  jwt:
    secret: dlrjgozldgoqhffurh?zz #비밀의 키
    expiration : 8640000 #만료시간



