# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI # WorkFolw name

on:
  push:
    # develop 브랜치에서 release 브랜치로 푸시되는 경우를 트리거
    branches:
      - 'release'  # release 브랜치로 푸시될 때
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'  # 태그 push에도 트리거

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build and release'
        required: true
        default: '1.0.0'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: maven

      #GIT Ubuntu 환경에서의 Maven을 캐싱하여 CI 속도 개선
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-     

      #clean install을 사용하여 Jacoco테스트부터 빌드가 되는지까지 확인  
    - name: Build with Maven
      run: mvn clean install

    - name: Upload Jacoco Report
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/index.html

      # Jacoco 리포트에서 커버리지 비율 추출하여 커버리지가 90% 미만이면 실패 처리
    - name: Check coverage threshold
      run: |
        coverage=$(awk '/<span class="percentage">/ {print $2}' target/site/jacoco/index.html | sed 's/%//')

        if [ "$coverage" -lt 90 ]; then
          echo "Coverage is below 90%: $coverage%"
          exit 1
        else
          echo "Coverage is above 90%: $coverage%"
        fi
